<a href="https://colab.research.google.com/github/malharinamdar/ml-tutorial/blob/main/broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

it is honestly very simple to perform mathematical calc in python for ml tasks

In [6]:
import numpy as np

A=np.array([[56.0,0.0,4.4,68.0],      #we know this is 3 x 4 matrix where rows are carbs protein fat calories and columns are the 4 foods of 100g each
            [1.2,104.0,52.0,8.0],
            [1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [8]:
#to sum the values of each vertical column we use following


cal=A.sum(axis=0)  #here axis=0 means vertically adding columnwise(vertically) axis=1 means adding horizontally rowwise
print(cal)

[ 59.  239.  155.4  76.9]


In [10]:
#now we want to calc the percentage of each nutrient' calories wrt to total calories

percentage=A/cal*100    # here we know the dimensions of matrix cal is (1,4) if we didnt know then we use cal.reshape(1,4) command
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
