In [1]:
import numpy as np

#ranked vector which causes issues
a=np.random.rand(5)
print(a)

#diff bw rand and randn is the value each of them generates from the distribution.
#rand generates random values and randn generates from bw (0,1)

[0.07981077 0.98217746 0.34876118 0.48013791 0.77651034]


In [3]:
print(a.shape)   #issue is that such ranked matrices have no structure and scope, they are random

(5,)


In [4]:
a=a.reshape(5,1) #we can reshape the array matrix into a column or row vector which is better than ranked matrices
print(a.shape)

(5, 1)


In [5]:
print(a)

[[0.07981077]
 [0.98217746]
 [0.34876118]
 [0.48013791]
 [0.77651034]]


In [6]:
b=np.random.randn(5,1)
print(b)

[[ 0.23909372]
 [-0.36094841]
 [ 2.21015027]
 [-0.78503802]
 [ 0.44618673]]


In [7]:
b=b.reshape(1,5)
print(b)

[[ 0.23909372 -0.36094841  2.21015027 -0.78503802  0.44618673]]


In [9]:
print(b.T) #TRANSPOSE

[[ 0.23909372]
 [-0.36094841]
 [ 2.21015027]
 [-0.78503802]
 [ 0.44618673]]


In [8]:
print(np.dot(b,b.T))

[[5.88758106]]


In [14]:
assert(b.shape == (1,5))